name: .NET Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore
      run: dotnet restore eVOL.sln

    - name: Build API
      run: dotnet build src/eVOL.Api/eVOL.Api.csproj --no-restore --configuration Debug

    - name: Build Application
      run: dotnet build src/eVOL.Application/eVOL.Application.csproj --no-restore --configuration Debug

    - name: Build Domain
      run: dotnet build src/eVOL.Domain/eVOL.Domain.csproj --no-restore --configuration Debug

    - name: Build Infrastructure
      run: dotnet build src/eVOL.Infrastructure/eVOL.Infrastructure.csproj --no-restore --configuration Debug

    - name: Build Workers
      run: dotnet build src/eVOL.Workers/eVOL.Workers.csproj --no-restore --configuration Debug
